version: '3'

services:
  mysqldb:
    container_name: mysqldb
    image: mohammedazhaf/chabiba:mysql8
    networks:
      - jwtbd-network
    environment:
      - MYSQL_DATABASE=chabiba_support
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqldb:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306

  chabiba_support:
    container_name: chabiba_support
    image: mohammedazhaf/chabiba:image-spring
    ports:
      - 8080:8080
    networks:
      - jwtbd-network
    depends_on:
      - mysqldb
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306

  chabiba_frontend:
    container_name: chabiba_frontend
    image: mohammedazhaf/chabiba:Frontend
    ports:
      - 4200:4200
    networks:
      - jwtbd-network
    depends_on:
      - chabiba_support

networks:
  jwtbd-network:
    name: jwtbd-network

volumes:
  mysqldb:
