version: '3.7'

# Define services
services:
  # App backend service
  spring-boot-app:
    image: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/chabiba_support
    depends_on:
      - db

  #  # Frontend Service
  #  react-app:
  #    image: my-app-react
  #    ports:
  #      - "3000:3000"
  #    environment:
  #      - REACT_APP_PORT=3000
  #      - REACT_APP_API=8080
  #    depends_on:
  #      - spring-boot-app

  # Database Service (Mysql)
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE = root
    ports:
      - "3307:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
volumes:
  mysql:
    external : true
    name : mysql